package com.animania.farm;

import java.util.List;
import java.util.Set;

/** IDs extracted from the pinned 1.12 registration calls. */
public final class FarmLegacyIds {
    public static final List<String> ALL = List.of(
            "buck_alpine",
            "buck_angora",
            "buck_fainting",
            "buck_kiko",
            "buck_kinder",
            "buck_nigerian_dwarf",
            "buck_pygmy",
            "bull_angus",
            "bull_friesian",
            "bull_hereford",
            "bull_highland",
            "bull_holstein",
            "bull_jersey",
            "bull_longhorn",
            "bull_mooshroom",
            "calf_angus",
            "calf_friesian",
            "calf_hereford",
            "calf_highland",
            "calf_holstein",
            "calf_jersey",
            "calf_longhorn",
            "calf_mooshroom",
            "cart",
            "chick_leghorn",
            "chick_orpington",
            "chick_plymouth_rock",
            "chick_rhode_island_red",
            "chick_wyandotte",
            "cow_angus",
            "cow_friesian",
            "cow_hereford",
            "cow_highland",
            "cow_holstein",
            "cow_jersey",
            "cow_longhorn",
            "cow_mooshroom",
            "doe_alpine",
            "doe_angora",
            "doe_fainting",
            "doe_kiko",
            "doe_kinder",
            "doe_nigerian_dwarf",
            "doe_pygmy",
            "ewe_dorper",
            "ewe_dorset",
            "ewe_friesian",
            "ewe_jacob",
            "ewe_merino",
            "ewe_suffolk",
            "foal_draft",
            "hen_leghorn",
            "hen_orpington",
            "hen_plymouth_rock",
            "hen_rhode_island_red",
            "hen_wyandotte",
            "hog_duroc",
            "hog_hampshire",
            "hog_large_black",
            "hog_large_white",
            "hog_old_spot",
            "hog_yorkshire",
            "kid_alpine",
            "kid_angora",
            "kid_fainting",
            "kid_kiko",
            "kid_kinder",
            "kid_nigerian_dwarf",
            "kid_pygmy",
            "lamb_dorper",
            "lamb_dorset",
            "lamb_friesian",
            "lamb_jacob",
            "lamb_merino",
            "lamb_suffolk",
            "mare_draft",
            "piglet_duroc",
            "piglet_hampshire",
            "piglet_large_black",
            "piglet_large_white",
            "piglet_old_spot",
            "piglet_yorkshire",
            "ram_dorper",
            "ram_dorset",
            "ram_friesian",
            "ram_jacob",
            "ram_merino",
            "ram_suffolk",
            "rooster_leghorn",
            "rooster_orpington",
            "rooster_plymouth_rock",
            "rooster_rhode_island_red",
            "rooster_wyandotte",
            "sow_duroc",
            "sow_hampshire",
            "sow_large_black",
            "sow_large_white",
            "sow_old_spot",
            "sow_yorkshire",
            "stallion_draft",
            "tiller",
            "wagon"
    );
    public static final Set<String> VEHICLE_IDS = Set.of("cart", "tiller", "wagon");

    public static boolean isVehicle(String id) {
        return VEHICLE_IDS.contains(id);
    }

    private FarmLegacyIds() {}
}
