package com.animania.data;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import net.minecraft.data.CachedOutput;
import net.minecraft.data.DataProvider;
import net.minecraft.data.PackOutput;
import net.minecraft.resources.ResourceLocation;

import java.nio.file.Path;
import java.util.concurrent.CompletableFuture;

/** Baseline server data generated by the Forge data run. */
public final class AnimaniaDataProvider implements DataProvider {
    private final PackOutput output;

    public AnimaniaDataProvider(PackOutput output) {
        this.output = output;
    }

    @Override
    public CompletableFuture<?> run(CachedOutput cache) {
        PackOutput.PathProvider tags = output.createPathProvider(PackOutput.Target.DATA_PACK, "tags/items");
        PackOutput.PathProvider recipes = output.createPathProvider(PackOutput.Target.DATA_PACK, "recipes");
        JsonObject feed = new JsonObject();
        feed.addProperty("replace", false);
        JsonArray values = new JsonArray();
        values.add("minecraft:wheat");
        values.add("minecraft:carrot");
        values.add("minecraft:potato");
        values.add("minecraft:beetroot");
        values.add("minecraft:wheat_seeds");
        values.add("minecraft:hay_block");
        feed.add("values", values);

        JsonObject manual = new JsonObject();
        manual.addProperty("type", "minecraft:crafting_shaped");
        JsonArray pattern = new JsonArray();
        pattern.add("PPP");
        pattern.add("PMP");
        pattern.add("PPP");
        manual.add("pattern", pattern);
        JsonObject key = new JsonObject();
        JsonObject paper = new JsonObject();
        paper.addProperty("item", "minecraft:paper");
        JsonObject book = new JsonObject();
        book.addProperty("item", "minecraft:book");
        key.add("P", paper);
        key.add("M", book);
        manual.add("key", key);
        JsonObject result = new JsonObject();
        result.addProperty("item", "animania:manual");
        manual.add("result", result);

        CompletableFuture<?> first = DataProvider.saveStable(cache, feed, tags.json(new ResourceLocation("animania", "animal_feed")));
        CompletableFuture<?> second = DataProvider.saveStable(cache, manual, recipes.json(new ResourceLocation("animania", "manual")));
        return CompletableFuture.allOf(first, second);
    }

    @Override
    public String getName() {
        return "Animania data";
    }
}

