package com.animania.catsdogs;

import java.util.List;

/** IDs extracted from the pinned 1.12 registration calls. */
public final class CatsDogsLegacyIds {
    public static final List<String> ALL = List.of(
            "female_blood_hound",
            "female_chihuahua",
            "female_collie",
            "female_corgi",
            "female_dachshund",
            "female_fox",
            "female_german_shepherd",
            "female_great_dane",
            "female_greyhound",
            "female_husky",
            "female_labrador",
            "female_pomeranian",
            "female_poodle",
            "female_pug",
            "female_wolf",
            "kitten_american_shorthair",
            "kitten_asiatic",
            "kitten_exotic",
            "kitten_norwegian",
            "kitten_ocelot",
            "kitten_ragdoll",
            "kitten_siamese",
            "kitten_tabby",
            "male_blood_hound",
            "male_chihuahua",
            "male_collie",
            "male_corgi",
            "male_dachshund",
            "male_fox",
            "male_german_shepherd",
            "male_great_dane",
            "male_greyhound",
            "male_husky",
            "male_labrador",
            "male_pomeranian",
            "male_poodle",
            "male_pug",
            "male_wolf",
            "puppy_blood_hound",
            "puppy_chihuahua",
            "puppy_collie",
            "puppy_corgi",
            "puppy_dachshund",
            "puppy_fox",
            "puppy_german_shepherd",
            "puppy_great_dane",
            "puppy_greyhound",
            "puppy_husky",
            "puppy_labrador",
            "puppy_pomeranian",
            "puppy_poodle",
            "puppy_pug",
            "puppy_wolf",
            "queen_american_shorthair",
            "queen_asiatic",
            "queen_exotic",
            "queen_norwegian",
            "queen_ocelot",
            "queen_ragdoll",
            "queen_siamese",
            "queen_tabby",
            "tom_american_shorthair",
            "tom_asiatic",
            "tom_exotic",
            "tom_norwegian",
            "tom_ocelot",
            "tom_ragdoll",
            "tom_siamese",
            "tom_tabby"
    );

    private CatsDogsLegacyIds() {}
}
